name: 'Production'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout master'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: cd ./browser && npm install
    - name: 'Run build'
      run: cd ./browser && npm run build
    - name: 'Generate release'
      run: cd ./browser && npm run generate-release token=${{ secrets.GITHUB_ACCESS_TOKEN }}
    - name: 'Upload to Chrome store'
      uses: trmcnvn/chrome-addon@v1
      with:
        extension: ${{ secrets.CHROME_EXTENSION_ID }}
        zip: ./dist/chrome.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
    - name: 'Upload to Firefox store'
      uses: trmcnvn/firefox-addon@v1
      with:
        uuid: ${{ secrets.FIREFOX_EXTENSION_ID }}
        xpi: ./dist/firefox.zip
        manifest: ./build/firefox/manifest.json
        api-key: ${{ secrets.FIREFOX_CLIENT_ID }}
        api-secret: ${{ secrets.FIREFOX_CLIENT_SECRET }}
    - name: 'Upload to Pale Moon store'
      uses: rafaelgssa/palemoon-addon@releases/v1
      with:
        slug: ${{ secrets.PALEMOON_EXTENSION_SLUG }}
        xpi: ./dist/palemoon.xpi
        username: ${{ secrets.PALEMOON_USERNAME }}
        password: ${{ secrets.PALEMOON_PASSWORD }}